// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efcore.Models
{
    public partial class Person
    {
        /// <summary>
        /// 일련번호
        /// </summary>
        public int DbId { get; set; }
        /// <summary>
        /// 이름
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 나이
        /// </summary>
        public int Age { get; set; }
        /// <summary>
        /// 이메일주소
        /// </summary>
        public string MailAddress { get; set; }
    }
}